import Head from "next/head";

import Message from "../components/Message";

import { useEffect, useState } from "react";

import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";

import Link from "next/link";

import { motion as m } from "framer-motion";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));

    return onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.75, ease: "easeOut" }}
    >
      <Head>
        <title>Artemix Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg font-medium">
        <h2>See what other people are saying</h2>
        {allPosts.map((post, index) => (
          <Message key={post.id} {...post} i={index}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button>{post.comments?.length || 0} comments</button>
            </Link>
          </Message>
        ))}
      </div>
    </m.div>
  );
}
